### ISSUE TITLE
cupy.cuda.compiler.CompileException: nvrtc: error: failed to load builtins

### ISSUE THREAD

**Issue by neelkadia-zz** [yusuketomoto/chainer-fast-style#106]
First of all thanks you did an amazing job!

I've tried to run the repo, CPU version is running normally took 553 sec fr 1080p image. But GPU version is giving me below error. Can you help?

```
Traceback (most recent call last):
  File "generate.py", line 45, in <module>
    y = model(x)
  File "/home/kadia/Documents/chainer-fast-neuralstyle-resize-conv/net.py", line 55, in __call__
    h = self.b1(F.elu(self.c1(x)))
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/activation/elu.py", line 116, in elu
    return ELU(alpha=alpha).apply((x,))[0]
  File "/usr/local/lib/python2.7/dist-packages/chainer/function_node.py", line 258, in apply
    outputs = self.forward(in_data)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function_node.py", line 367, in forward
    return self.forward_gpu(inputs)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/activation/elu.py", line 34, in forward_gpu
    x[0], self.alpha)
  File "cupy/core/elementwise.pxi", line 592, in cupy.core.core.ElementwiseKernel.__call__
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret
  File "cupy/core/elementwise.pxi", line 443, in cupy.core.core._get_elementwise_kernel
  File "cupy/core/elementwise.pxi", line 13, in cupy.core.core._get_simple_elementwise_kernel
  File "cupy/core/elementwise.pxi", line 33, in cupy.core.core._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 146, in cupy.core.core.compile_with_cache
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 135, in compile_with_cache
    base = _preprocess('', options, arch)
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 98, in _preprocess
    result = prog.compile(options)
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 245, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: nvrtc: error: failed to load builtins
```

**Comment by neelkadia-zz** [comment]
Closing this issue. Solved by just reconfiguring the CUDA on system

**Comment by viralbthakar** [comment]
@neelkadia What did you do to solve the issue? By re-configuring you mean re-installing? I am facing the same error, can you please guide me.

**Comment by Orkat** [comment]
Try `export LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"`

**Comment by Prologueyan** [comment]
@Orkat  thanks for your answer ，but why this work？

**Comment by prologueyan-hr** [comment]
@neelkadia  How did you solve this question ？I have met same issue

**Comment by mboisson** [comment]
LD_LIBRARY_PATH is not supposed to be used in a production setting. This is not a good option.
