### ISSUE TITLE
error in sh setup_model.sh

### ISSUE THREAD

**Issue by yep-hy** [yusuketomoto/chainer-fast-style#98]
macdeMacBook-Pro:chainer-fast-neuralstyle-master yep$ sh setup_model.sh
load VGG16 caffemodel
Traceback (most recent call last):
  File "create_chainer_model.py", line 34, in <module>
    ref = CaffeFunction('VGG_ILSVRC_16_layers.caffemodel')
  File "/usr/local/lib/python3.6/site-packages/chainer/links/caffe/caffe_function.py", line 139, in __init__
    net.MergeFromString(model_file.read())
  File "/usr/local/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 1063, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 1089, in InternalParse
    new_pos = local_SkipField(buffer, new_pos, end, tag_bytes)
  File "/usr/local/lib/python3.6/site-packages/google/protobuf/internal/decoder.py", line 850, in SkipField
    return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
  File "/usr/local/lib/python3.6/site-packages/google/protobuf/internal/decoder.py", line 820, in _RaiseInvalidWireType
    raise _DecodeError('Tag had invalid wire type.')
google.protobuf.message.DecodeError: Tag had invalid wire type.

**Comment by rainbow979** [comment]
helphelp
