### ISSUE TITLE
RuntimeError: CUDA environment is not correctly set up

### ISSUE THREAD

**Issue by lijiansong** [yusuketomoto/chainer-fast-style#99]
RuntimeError: CUDA environment is not correctly set up

Traceback (most recent call last):
  File "train.py", line 90, in <module>
    cuda.get_device(args.gpu).use()
  File "/usr/local/lib/python2.7/dist-packages/chainer/cuda.py", line 212, in get_device
    return _get_device(*args)
  File "/usr/local/lib/python2.7/dist-packages/chainer/cuda.py", line 218, in _get_device
    check_cuda_available()
  File "/usr/local/lib/python2.7/dist-packages/chainer/cuda.py", line 79, in check_cuda_available
    raise RuntimeError(msg)

**Comment by lijiansong** [comment]
see here  https://github.com/chainer/chainer#installation,
To enable CUDA support, set up CUDA and install CuPy.

```
$ pip install cupy
```
